# Generated by Django 6.0 on 2025-12-16 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('gestor', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('linguagem', 'Linguagem'), ('framework', 'Framework'), ('cloud', 'Serviço Cloud'), ('banco', 'Banco de Dados'), ('outros', 'Outros')], max_length=50)),
                ('versao', models.CharField(blank=True, max_length=50, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_execucao', 'Em Execução'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20)),
                ('orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('risco', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='baixo', max_length=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='gestao.departamento')),
                ('tecnologias', models.ManyToManyField(related_name='projetos', to='gestao.tecnologia')),
            ],
        ),
    ]
